volumes:
  postgres-data:
    external: true
  pgadmin:
    external: true 
services:
  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=users
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432
  api-yelp:
    build:
      context: ./api-yelp
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api-yelp:/app
    environment:
      DATABASE_URL: postgresql://users:password@postgres/users
      WAIT_HOSTS: postgres:5432
      API_YELP_KEY: ${API_YELP_KEY}
  user:
    build:
      context: ./user
      dockerfile: ./Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./user:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://users:password@postgres/users
      WAIT_HOSTS: postgres:5432
      DJWTO_SIGNING_KEY: 26e7594eaae00351c1beeed9f357e35c12d7d3c86d3a90175f747a5892dff30a
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_YELP: http://localhost:8000
      REACT_APP_USER: http://localhost:8001
      REACT_APP_THIRD_PARTY_SERVICE: https://api.yelp.com/v3
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: person@email.com
      PGADMIN_DEFAULT_PASSWORD: password
      