# Generated by Django 4.0.3 on 2022-08-08 23:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=30, null=True)),
                ('business_name', models.CharField(max_length=100, null=True)),
                ('business_image', models.URLField(null=True)),
                ('business_rating', models.FloatField(null=True)),
                ('business_price', models.CharField(max_length=5, null=True)),
                ('business_display_address', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('business_id', 'user')},
            },
        ),
    ]
